cleaning

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -8,32 +8,53 @@ export EXPORT_PATH="$SCRAPYD_INSTALL/http_files"
 export SPIDERS_PATH="$SCRAPYD_INSTALL/spiders"
 export SUPERVISOR_LOGS="/var/log/supervisor"
 
-createUserAndPaths() {
+set_globalvars(){
+	{
+		echo "alias iniSpiders=''"
+		echo "export SCRAPYD_USER=\"${SCRAPYD_USER}\""
+	 	echo "export SCRAPYD_API=\"${SCRAPYD_API}\""
+		echo "export SCRAPYD_CONF=\"${SCRAPYD_CONF}\""
+		echo "export SCRAPYD_INSTALL=\"${SCRAPYD_INSTALL}\""
+		echo "export SCRAPYD_LOGS=\"${SCRAPYD_LOGS}\""
+		echo "export EXPORT_PATH=\"${EXPORT_PATH}\""
+		echo "export SPIDERS_PATH=\"${SPIDERS_PATH}\""
+		echo "export SUPERVISOR_LOGS=\"${SUPERVISOR_LOGS}\""
+	} >> /etc/profile
+}
+
+make_dirs(){
+	mkdir -p "$SCRAPYD_INSTALL/eggs" \
+					 "$SCRAPYD_INSTALL/dbs" \
+					 "$SCRAPYD_INSTALL/logs" \
+					 "$EXPORT_PATH" \
+					 "$SPIDERS_PATH" \
+					 "$SUPERVISOR_LOGS"
+	chown -R "${SCRAPYD_USER}:${SCRAPYD_USER}" "${SCRAPYD_CONF}" \
+																						 "${SCRAPYD_INSTALL}" \
+																						 "${SPIDERS_PATH}" \
+																						 "${EXPORT_PATH}" \
+																						 "$SUPERVISOR_LOGS"
+}
+
+createUser() {
 	if ! egrep -q "^${SCRAPYD_USER}:x:999:${SCRAPYD_USER}$" /etc/group; then
-		u_home="/home/${SCRAPYD_USER}"
 		printf "\nCreate user %s..." "${SCRAPYD_USER}:${SCRAPYD_USER}"
+
+		mkdir -p "/home/${SCRAPYD_USER}"
 		addgroup -g 999 "${SCRAPYD_USER}" || printf "\nFail to create group!"
-		adduser -h "$u_home" -u 999 -G "${SCRAPYD_USER}" -s "/bin/sh" -D "${SCRAPYD_USER}" || printf "\nFail to create user!"
-		curl -sSL "https://github.com/scrapy/scrapy/raw/master/extras/scrapy_bash_completion" >> "$u_home/.bashrc"
-		#touch "${SPIDERS_CRON}"
-		#crontab -u "${SCRAPYD_USER}" "${SPIDERS_CRON}"
-		mkdir -p "$SCRAPYD_INSTALL/eggs" "$SCRAPYD_INSTALL/dbs" "$SCRAPYD_INSTALL/logs" "$EXPORT_PATH" "$SPIDERS_PATH" "$SUPERVISOR_LOGS"
-		chown -R "${SCRAPYD_USER}:${SCRAPYD_USER}" "${SCRAPYD_CONF}" "${SCRAPYD_INSTALL}" "${SPIDERS_PATH}" "${EXPORT_PATH}" "$u_home" "$SUPERVISOR_LOGS/scrapyd" # "${SPIDERS_CRON}"
-		
-		{
-			echo "export SCRAPYD_USER=\"${SCRAPYD_USER}\""
-		 	echo "export SCRAPYD_API=\"${SCRAPYD_API}\""
-			echo "export SCRAPYD_CONF=\"${SCRAPYD_CONF}\""
-			echo "export SCRAPYD_INSTALL=\"${SCRAPYD_INSTALL}\""
-			echo "export SCRAPYD_LOGS=\"${SCRAPYD_LOGS}\""
-			echo "export EXPORT_PATH=\"${EXPORT_PATH}\""
-			echo "export SPIDERS_PATH=\"${SPIDERS_PATH}\""
-			echo "export SUPERVISOR_LOGS=\"${SUPERVISOR_LOGS}\""
-		} >> /etc/profile
+		adduser -h "/home/${SCRAPYD_USER}" \
+						-u 999 \
+						-G "${SCRAPYD_USER}" \
+						-s "/bin/sh" \
+						-D "${SCRAPYD_USER}" || printf "\nFail to create user!"
+		chown -R "${SCRAPYD_USER}:${SCRAPYD_USER}" "/home/${SCRAPYD_USER}"
 	fi
 }
 
 writeScrapydConfig() {
+	if test ! -f "/etc/scrapyd/supervisord.conf"; then
+		ln -s "/etc/supervisord.conf" "$SCRAPYD_CONF/supervisord.conf"
+	fi
 	if test ! -f "$SCRAPYD_CONF/scrapyd.conf"; then
 		printf "\nWriting %s/scrapyd.conf..." "$SCRAPYD_CONF"
 		# items_dir   = $SCRAPYD_INSTALL/items
@@ -105,26 +126,12 @@ writeScrapydConfig() {
 #   done
 # }
 
-# registerSpiders() {
-# 	script=$(which spiders.py)
-# 	runp "$script" initSpiders
-# 	return $?
-# }
-
-# installSpiders(){
-# 	printf "\n"
-# 	sleep 5
-# 	# TODO waitForFile <file> <pattern> <10>
-# 	while read -r spider || [[ -n "$spider" ]]; do
-#     deployGitSpider "$spider" || printf "\nError deploying %s" "$spider" 1>&2
-# 	done < "$SPIDERS_FILE"
-# }
-
 print_help() {
 	printf "\nUsage :"
 	printf "\ndocker <create|run [--rm]> -v </host/path/to/scrapyd/config>:%s\
  -v </host/path/to/scrapyd/data>:%s\
  -v </host/path/to/logs>:$SUPERVISOR_LOGS\
+ -e SCRAPYD_USER=<scrapyd_user>\
  -p <http_port>:8000\
  -p <scrapyd_api_port>:6800]\
  --name <my-scrapyd>\
@@ -136,9 +143,12 @@ print_help() {
 main() {
 	case "$1" in
 		scrapyd )
-			createUserAndPaths
-			writeScrapydConfig
-			printf "\n" && exec supervisord -c /etc/supervisord.conf
+			set_globalvars \
+				&& createUser \
+				&& make_dirs \
+				&& writeScrapydConfig || exit 1
+			printf "\n" \
+				&& exec supervisord -c /etc/scrapyd/supervisord.conf
 			;;
 		help|* )
 			print_help
